#!/usr/bin/env python3
"""
Regenerate wiki/index.md and app/data/wiki-index.json from the YAML
frontmatter of every markdown page under wiki/.

Run:
    python tools/build_index.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml  # PyYAML

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / "wiki"
INDEX_MD = WIKI / "index.md"
INDEX_JSON = ROOT / "app" / "data" / "wiki-index.json"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)

SECTION_ORDER = [
    "overview", "tour", "architecture", "concept", "glossary", "log",
    "repo", "monitor", "arbiter", "service", "common-util", "module",
    "api-domain", "route-group", "pipeline",
]
SECTION_LABELS = {
    "overview": "Start here",
    "tour": "Tours",
    "architecture": "Architecture",
    "concept": "Concepts",
    "glossary": "Glossary",
    "log": "Activity log",
    "repo": "Repositories",
    "monitor": "Monitors (Lumi-AI-Continuous)",
    "arbiter": "Arbiters (Lumi-AI-Continuous)",
    "service": "Services (Lumi-AI-Continuous)",
    "common-util": "Common utils (Lumi-AI-Continuous)",
    "module": "V2 Modules (Lumi-AI-Core)",
    "api-domain": "API Domains (lumi-web-v2)",
    "route-group": "Route Groups (lumi-web-v2)",
    "pipeline": "Pipelines",
    "uncategorised": "Other",
}


def parse_frontmatter(text: str) -> tuple[dict[str, Any] | None, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None, text
    try:
        data = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None, text
    return data, text[m.end():]


def collect_pages() -> list[dict[str, Any]]:
    pages: list[dict[str, Any]] = []
    for md in sorted(WIKI.rglob("*.md")):
        if md.name == "index.md":
            continue
        rel = md.relative_to(ROOT).as_posix()
        try:
            text = md.read_text(encoding="utf-8")
        except Exception:
            continue
        fm, _body = parse_frontmatter(text)
        page = {
            "path": rel,
            "name": (fm or {}).get("name") or md.stem.replace("-", " ").title(),
            "description": (fm or {}).get("description", ""),
            "type": (fm or {}).get("type", "uncategorised"),
            "tags": (fm or {}).get("tags", []) or [],
            "graph_node": (fm or {}).get("graph_node"),
            "has_frontmatter": fm is not None,
        }
        pages.append(page)
    return pages


def write_index_md(pages: list[dict[str, Any]]) -> None:
    by_type: dict[str, list[dict[str, Any]]] = {}
    for p in pages:
        by_type.setdefault(p["type"], []).append(p)

    lines: list[str] = [
        "---",
        "name: Wiki Index",
        "description: Auto-generated catalog of every page in the wiki.",
        "type: overview",
        "---",
        "",
        "# Wiki Index",
        "",
        "_Auto-generated by `tools/build_index.py` — do not hand-edit._",
        "",
    ]
    ordered_types = SECTION_ORDER + [t for t in by_type if t not in SECTION_ORDER]
    for t in ordered_types:
        if t not in by_type:
            continue
        lines.append(f"## {SECTION_LABELS.get(t, t.title())}")
        lines.append("")
        for p in sorted(by_type[t], key=lambda x: x["name"].lower()):
            rel_from_index = Path(p["path"]).relative_to("wiki").as_posix()
            desc = p["description"]
            stub_marker = " *(stub)*" if not p["has_frontmatter"] else ""
            lines.append(f"- [{p['name']}]({rel_from_index}) — {desc}{stub_marker}")
        lines.append("")

    INDEX_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index_json(pages: list[dict[str, Any]]) -> None:
    INDEX_JSON.parent.mkdir(parents=True, exist_ok=True)
    INDEX_JSON.write_text(
        json.dumps({"pages": pages, "count": len(pages)}, indent=2),
        encoding="utf-8",
    )


def main() -> None:
    pages = collect_pages()
    write_index_md(pages)
    write_index_json(pages)
    missing_fm = sum(1 for p in pages if not p["has_frontmatter"])
    print(f"Indexed {len(pages)} pages. {missing_fm} missing frontmatter.")
    print(f"  → wiki/index.md")
    print(f"  → app/data/wiki-index.json")


if __name__ == "__main__":
    main()
